create table person
(
    id        integer generated by default as identity,
    full_name varchar not null,
    title     varchar not null,
    age       integer not null,
    primary key (id)
);

alter table person
    owner to postgres;

create table book
(
    id         integer generated by default as identity,
    user_id    integer,
    title      varchar not null,
    author     varchar not null,
    page_count integer not null,
    primary key (id),
    constraint book_fk
        foreign key (user_id) references person
);

alter table book
    owner to postgres;