create table ulab_edu.person
(
    id        integer generated by default as identity,
    full_name varchar(50) not null,
    title     varchar(50) not null,
    age       integer     not null,
    primary key (id)
);

comment on table ulab_edu.person is 'Справочник используется для хранения пользователей';
comment on column ulab_edu.person.id is 'Идентификатор пользователя';
comment on column ulab_edu.person.full_name is 'Полное имя';
comment on column ulab_edu.person.title is 'Должность';
comment on column ulab_edu.person.age is 'Возраст';
