create table ulab_edu.book
(
    id         integer generated by default as identity,
    user_id    integer,
    title      varchar not null,
    author     varchar not null,
    page_count integer not null,
    primary key (id),
    constraint book_fk
        foreign key (user_id) references ulab_edu.person
);

comment on table ulab_edu.book is 'Справочник используется для хранения книг';
comment on column ulab_edu.book.id is 'Идентификатор книги';
comment on column ulab_edu.book.user_id is 'Идентификатор пользователя';
comment on column ulab_edu.book.title is 'Заголовок';
comment on column ulab_edu.book.author is 'Автор';
comment on column ulab_edu.book.page_count is 'Количество страниц';
